### ISSUE TITLE
Improve style in Safari

### ISSUE THREAD

**Issue by fregante** [fregante/webext-base-css#10]
## Current
 
<img width="699" alt="Screen Shot 5" src="https://user-images.githubusercontent.com/1402241/176886910-ea83bb52-4b9b-467c-9d1a-ca8ef0404cfb.png">

## Desired

<img width="700" alt="Screen Shot 4" src="https://user-images.githubusercontent.com/1402241/176886950-3251eb5d-5f99-4c4f-9cdf-d59614360ba5.png">

Using:

```css
html {
  background: Canvas;
}
input, textarea {
  appearance: textfield
}
```

Spacing can be improved further too. 

The system styles and colors look nice in dark mode, but `textfield` has nearly zero contrast in light mode:

<img width="139" alt="Screen Shot 7" src="https://user-images.githubusercontent.com/1402241/176887270-eed78b04-dc08-4384-8f17-5c18f74154e3.png">

`textfield` is usually used on light gray on macOS, so it'd be great to find the right `background` variable to match that

<img width="76" alt="Screen Shot 8" src="https://user-images.githubusercontent.com/1402241/176887421-f908e556-90e9-4815-83f4-987a9db14768.png">

Also `font:-apple-system-body` would be nice

## Related

- https://blog.jim-nielsen.com/2021/css-system-colors/
- https://www.stefanjudis.com/today-i-learned/css-defines-color-values-that-follow-system-preferences/
- https://css-tricks.com/system-things/

**Comment by fregante** [comment]
Found the color: `Window`

<img width="188" alt="Screen Shot 9" src="https://user-images.githubusercontent.com/1402241/176888533-ed646301-c83e-4898-a1e6-97899e359319.png">

- http://www.iangraham.org/books/xhtml1/appd/update-23feb2000.html

**Comment by fregante** [comment]
<img width="108" alt="Screen Shot 15" src="https://user-images.githubusercontent.com/1402241/177953983-590b5657-c416-470d-ba95-e4ef18f4aa97.png"> <img width="108" alt="Screen Shot 14" src="https://user-images.githubusercontent.com/1402241/177954004-635e5bcd-837d-42da-8d01-c24a0c5f3891.png">


This is the core CSS needed by Safari,:

```css
:root {
	color-scheme: light dark;
	background: Window;
	font:-apple-system-body;
	max-width: 700px;
	margin: auto;
	line-height: 1.5;
}
body {
	--body-margin-h: 15px;
	margin: var(--body-margin-h);
}

a {
	color: #8ab4f8
}


/* Selector matches Firefox’ */
input[type='number'],
input[type='password'],
input[type='search'],
input[type='text'],
input[type='url'],
input:not([type]),
textarea {
	display: block;
	box-sizing: border-box;
	margin-left: 0;
	width: 100%;
	resize: vertical;
	tab-size: 4 !important;
	appearance: textfield;
	font-size: 1.2em;
	padding: 0.3em;
}


hr {
	margin-right: calc(-1 * var(--body-margin-h));
	margin-left: calc(-1 * var(--body-margin-h));
	border: none;
	border-bottom: 1px solid #aaa4;
}


img {
	vertical-align: middle;
}
```
